In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [3]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
df['target']=df['target'].apply(lambda x:iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
df[67:80]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
67                5.8               2.7                4.1               1.0   
68                6.2               2.2                4.5               1.5   
69                5.6               2.5                3.9               1.1   
70                5.9               3.2                4.8               1.8   
71                6.1               2.8                4.0               1.3   
72                6.3               2.5                4.9               1.5   
73                6.1               2.8                4.7               1.2   
74                6.4               2.9                4.3               1.3   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   

        target  
67  versicolor  
68  versicolor  
69  versicolor  
70  versicolor  
71  versicolor  
72  versicolor  
73  versicolor  
74  versicolor  
75  versicolor  
76  versicolor  
77  versicolor  
78  versicolor  
79  versicolor

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(iris.data,iris.target,test_size=0.3)

In [8]:
#using support vector machine
from sklearn.svm import SVC
m_svc=SVC(kernel='rbf',C=20,gamma='auto')
m_svc.fit(xtrain,ytrain)
m_svc.score(xtest,ytest)

0.9555555555555556

In [9]:
#using KFold cross validation
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [10]:
cross_val_score(SVC(kernel='poly',C=20,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [11]:
cross_val_score(SVC(kernel='linear',C=30,gamma='auto'),xtest,ytest,cv=5)

array([1.        , 0.88888889, 1.        , 0.88888889, 0.88888889])

In [12]:
#by SVM Model
kernals=['rbf','linear']
C=[1,10,20]
avg_score={}
for kval in kernals:
    for cval in C:
        cv=cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval + '_' + str(cval)]=np.average(cv)
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [13]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'), {
    'C': np.arange(1,10),
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00119128, 0.00020061, 0.0038794 , 0.00020876, 0.        ,
        0.00118151, 0.00139365, 0.00127363, 0.00053496, 0.00059409,
        0.00150385, 0.00019979, 0.        , 0.00449276, 0.00126481,
        0.00165377, 0.00061421, 0.00019927]),
 'std_fit_time': array([0.00098862, 0.00040121, 0.00486369, 0.00041752, 0.        ,
        0.00027461, 0.00088378, 0.00072984, 0.00044444, 0.00078836,
        0.00129829, 0.00039959, 0.        , 0.00580977, 0.00252962,
        0.00330753, 0.00082594, 0.00039854]),
 'mean_score_time': array([8.76617432e-04, 1.99413300e-04, 1.58977509e-04, 1.32861137e-03,
        0.00000000e+00, 5.88941574e-04, 4.85992432e-04, 2.45618820e-04,
        6.60467148e-04, 1.54023170e-03, 1.99890137e-04, 0.00000000e+00,
        0.00000000e+00, 4.05263901e-04, 2.11286545e-04, 2.41756439e-05,
        1.61571503e-03, 1.04441643e-03]),
 'std_score_time': array([9.50850089e-04, 3.98826599e-04, 3.17955017e-04, 2.65722275e-03,
        0.00000000e+00, 4.81

In [14]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.001191      0.000989         0.000877        0.000951       1   
1        0.000201      0.000401         0.000199        0.000399       1   
2        0.003879      0.004864         0.000159        0.000318       2   
3        0.000209      0.000418         0.001329        0.002657       2   
4        0.000000      0.000000         0.000000        0.000000       3   
5        0.001182      0.000275         0.000589        0.000481       3   
6        0.001394      0.000884         0.000486        0.000605       4   
7        0.001274      0.000730         0.000246        0.000491       4   
8        0.000535      0.000444         0.000660        0.000540       5   
9        0.000594      0.000788         0.001540        0.001717       5   
10       0.001504      0.001298         0.000200        0.000400       6   
11       0.000200      0.000400         0.000000        0.000000       6   
12       0.000000      0.000000         0.000000        0.000000       7   
13       0.004493      0.005810         0.000405        0.000496       7   
14       0.001265      0.002530         0.000211        0.000423       8   
15       0.001654      0.003308         0.000024        0.000048       8   
16       0.000614      0.000826         0.001616        0.002760       9   
17       0.000199      0.000399         0.001044        0.001324       9   

   param_kernel                        params  split0_test_score  \
0           rbf     {'C': 1, 'kernel': 'rbf'}           0.966667   
1        linear  {'C': 1, 'kernel': 'linear'}           0.966667   
2           rbf     {'C': 2, 'kernel': 'rbf'}           0.966667   
3        linear  {'C': 2, 'kernel': 'linear'}           0.966667   
4           rbf     {'C': 3, 'kernel': 'rbf'}           0.966667   
5        linear  {'C': 3, 'kernel': 'linear'}           0.966667   
6           rbf     {'C': 4, 'kernel': 'rbf'}           0.966667   
7        linear  {'C': 4, 'kernel': 'linear'}           0.966667   
8           rbf     {'C': 5, 'kernel': 'rbf'}           0.966667   
9        linear  {'C': 5, 'kernel': 'linear'}           1.000000   
10          rbf     {'C': 6, 'kernel': 'rbf'}           0.966667   
11       linear  {'C': 6, 'kernel': 'linear'}           1.000000   
12          rbf     {'C': 7, 'kernel': 'rbf'}           0.966667   
13       linear  {'C': 7, 'kernel': 'linear'}           1.000000   
14          rbf     {'C': 8, 'kernel': 'rbf'}           0.966667   
15       linear  {'C': 8, 'kernel': 'linear'}           1.000000   
16          rbf     {'C': 9, 'kernel': 'rbf'}           0.966667   
17       linear  {'C': 9, 'kernel': 'linear'}           1.000000   

    split1_test_score  split2_test_score  split3_test_score  \
0                 1.0           0.966667           0.966667   
1                 1.0           0.966667           0.966667   
2                 1.0           0.966667           0.966667   
3                 1.0           0.966667           0.966667   
4                 1.0           0.933333           0.966667   
5                 1.0           0.933333           0.966667   
6                 1.0           1.000000           0.966667   
7                 1.0           0.933333           0.966667   
8                 1.0           0.966667           0.966667   
9                 1.0           0.933333           0.966667   
10                1.0           0.966667           0.966667   
11                1.0           0.900000           0.966667   
12                1.0           0.966667           0.966667   
13                1.0           0.900000           0.966667   
14                1.0           0.966667           0.966667   
15                1.0           0.900000           0.966667   
16                1.0           0.966667           0.966667   
17                1.0           0.900000           0.966667   

    split4_test_score  mean_test_score  std_test_score  rank_test_sc

In [15]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2        2          rbf         0.980000
3        2       linear         0.980000
4        3          rbf         0.973333
5        3       linear         0.973333
6        4          rbf         0.986667
7        4       linear         0.973333
8        5          rbf         0.980000
9        5       linear         0.980000
10       6          rbf         0.980000
11       6       linear         0.973333
12       7          rbf         0.980000
13       7       linear         0.973333
14       8          rbf         0.980000
15       8       linear         0.973333
16       9          rbf         0.980000
17       9       linear         0.973333

In [16]:
clf.best_estimator_

SVC(C=4, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
clf.best_params_

{'C': 4, 'kernel': 'rbf'}

In [18]:
clf.best_score_

0.9866666666666667

In [19]:
clf.best_index_

6

In [20]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear             0.98
1       1          rbf             0.98

In [21]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [27]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,10,20]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,10,20]
        }
    }
}

In [28]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                  {'C': 10}

In [26]:
#Based on above, I can conclude that SVM with C=1 and kernel='rbf' is the best model for solving my problem of iris flower classification