In [21]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [22]:
df=pd.read_csv("C:\\Users\\dell\\OneDrive\\Desktop\\test_score.csv")

In [23]:
df

experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        NaN               7   72000
7          11        7.0               8   80000

In [37]:
import math
m=math.floor(df.testscore.mean())
m

7

In [38]:
df.testscore.fillna(m)

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: testscore, dtype: float64

In [39]:
df

experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000

In [40]:
df.testscore=df.testscore.fillna(m)
df

experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000

In [41]:
r=linear_model.LinearRegression()

In [42]:
r

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
r.fit(df[["experience","testscore","interviewscore"]],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
r.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [45]:
r.intercept_

17737.26346433771

In [46]:
r.predict([[2,9,6]])

array([53205.96797671])

In [47]:
r.predict([[12,10,10]])

array([92002.18340611])

In [48]:
df

experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000